import { test, expect } from '@playwright/test'

test('example library supports browsing, search, versions, editing, and mobile layout', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.setViewportSize({ width: 1440, height: 1100 })
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Library.' })).toBeVisible()
  await expect(page.getByLabel('Illustrative sample PDF preview')).toBeVisible()
  await page.screenshot({ path: 'test-results/local-dir-desktop.png', fullPage: true })
  await page.getByRole('button', { name: 'Versions of LE 01 — User manual', exact: true }).click()
  await expect(page.getByText('Version 1.1', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Overview', exact: true }).click()
  await page.getByRole('button', { name: 'Edit', exact: true }).click()
  await page.getByLabel('Title (optional)').fill('My edited sample manual')
  await page.getByRole('button', { name: 'Save details', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'My edited sample manual' })).toBeVisible()
  await page.getByRole('textbox', { name: 'Search library' }).fill('Listening notes')
  await expect(page.locator('.file-row')).toHaveCount(1)
  await page.getByRole('button', { name: 'View Listening notes', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'A space for listening' })).toBeVisible()
  await page.getByRole('textbox', { name: 'Search library' }).fill('zz-no-matches-zz')
  await expect(page.getByRole('heading', { name: 'Nothing here by that name.' })).toBeVisible()
  await page.getByRole('button', { name: 'Clear filters', exact: true }).click()
  await page.getByRole('button', { name: 'Grid view' }).click()
  await expect(page.locator('.file-card').first()).toBeVisible()
  await page.getByRole('button', { name: 'List view' }).click()
  await page.getByRole('button', { name: 'Add files', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Start with your directory' })).toBeVisible()
  await page.getByRole('button', { name: 'Cancel' }).click()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('button', { name: 'Open navigation' }).click()
  await page.getByRole('navigation', { name: 'Library navigation' }).getByRole('button', { name: /^Favorites/ }).click()
  await expect(page.getByRole('heading', { name: 'Favorites.' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await expect.poll(() => page.locator('.sidebar').evaluate(element => element.getBoundingClientRect().right)).toBeLessThanOrEqual(0)
  await page.screenshot({ path: 'test-results/local-dir-mobile.png', fullPage: true, animations: 'disabled' })
  expect(errors).toEqual([])
})

test('connected native filesystem persists imports, links, metadata and external discoveries', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.addInitScript(() => {
    // Only the OS picker is substituted. All handles, streams, files, JSON and
    // IndexedDB below use Chromium's real native origin-private filesystem.
    window.showDirectoryPicker = async () => {
      const storage = await navigator.storage.getDirectory()
      return storage.getDirectoryHandle('Local Dir test', { create: true })
    }
  })
  await page.goto('/')
  await page.evaluate(async () => {
    const storage = await navigator.storage.getDirectory()
    const root = await storage.getDirectoryHandle('Local Dir test', { create: true })
    const audio = await root.getDirectoryHandle('Audio', { create: true })
    const device = await audio.getDirectoryHandle('Device', { create: true })
    for (const [name, content] of [['device_v1.0.bin', 'older'], ['device_v2.0.bin', 'latest'], ['notes.md', '# Local notes\n\nReal files, local metadata.']]) {
      const file = await device.getFileHandle(name, { create: true })
      const writable = await file.createWritable()
      await writable.write(content)
      await writable.close()
    }
  })
  await page.getByRole('button', { name: 'Connect directory', exact: true }).click()
  await expect(page.locator('.demo-banner')).toHaveCount(0)
  await expect(page.locator('.file-row')).toHaveCount(2)
  await page.getByRole('button', { name: 'View notes', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Local notes', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Edit', exact: true }).click()
  await page.getByLabel('Title (optional)').fill('Device setup notes')
  await page.getByLabel('Manufacturer', { exact: true }).fill('Acme')
  await page.getByLabel('Tags').fill('setup, test')
  await page.getByRole('button', { name: 'Save details', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Device setup notes', exact: true })).toBeVisible()

  await page.getByRole('button', { name: 'Add link', exact: true }).click()
  await page.getByLabel('Title', { exact: true }).fill('Acme support')
  await page.getByLabel('URL', { exact: true }).fill('https://example.com/support')
  await page.getByLabel('Save in').fill('Audio/Device')
  await page.getByRole('dialog').getByRole('button', { name: 'Add link', exact: true }).click()
  await expect(page.getByRole('button', { name: 'View Acme support', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'View Acme support', exact: true }).click()
  await page.getByRole('button', { name: 'Edit', exact: true }).click()
  await page.getByLabel('URL', { exact: true }).fill('https://example.com/help')
  await page.getByRole('button', { name: 'Save details', exact: true }).click()
  await expect(page.getByRole('link', { name: 'Visit website', exact: true })).toHaveAttribute('href', 'https://example.com/help')

  await page.getByRole('button', { name: 'Add files', exact: true }).click()
  await page.getByLabel('Choose files to add', { exact: true }).setInputFiles({ name: 'notes.md', mimeType: 'text/markdown', buffer: Buffer.from('# Imported notes\n\nA different file.') })
  await page.getByLabel('Title (optional)').fill('Imported reference')
  await page.getByLabel('Save in').fill('Audio/Device')
  await page.getByRole('dialog').getByRole('button', { name: 'Add files', exact: true }).click()
  await expect(page.getByRole('button', { name: 'View Imported reference', exact: true })).toBeVisible()

  const disk = await page.evaluate(async () => {
    const root = await (await navigator.storage.getDirectory()).getDirectoryHandle('Local Dir test')
    const indexDir = await root.getDirectoryHandle('.localdir')
    const index = JSON.parse(await (await (await indexDir.getFileHandle('index.json')).getFile()).text())
    const device = await (await root.getDirectoryHandle('Audio')).getDirectoryHandle('Device')
    const original = await (await (await device.getFileHandle('notes.md')).getFile()).text()
    const imported = await (await (await device.getFileHandle('notes (2).md')).getFile()).text()
    return { index, original, imported }
  })
  expect(disk.original).toContain('Real files, local metadata.')
  expect(disk.imported).toContain('A different file.')
  expect(disk.index.files['Audio/Device/notes.md'].metadata.title).toBe('Device setup notes')
  expect(disk.index.files['Audio/Device/notes (2).md'].metadata.title).toBe('Imported reference')
  expect(Object.values(disk.index.links)).toEqual(expect.arrayContaining([expect.objectContaining({ title: 'Acme support', url: 'https://example.com/help' })]))

  await page.reload()
  await page.getByRole('button', { name: 'Reconnect directory', exact: true }).click()
  await expect(page.getByRole('button', { name: 'View Device setup notes', exact: true })).toBeVisible()
  await page.evaluate(async () => {
    const root = await (await navigator.storage.getDirectory()).getDirectoryHandle('Local Dir test')
    const device = await (await root.getDirectoryHandle('Audio')).getDirectoryHandle('Device')
    const writable = await (await device.getFileHandle('device_v3.0.bin', { create: true })).createWritable()
    await writable.write('added outside the app')
    await writable.close()
  })
  await page.getByRole('button', { name: 'Rescan directory', exact: true }).click()
  await expect(page.locator('.file-version').filter({ hasText: 'v3.0' })).toBeVisible()
  await page.getByRole('button', { name: 'Create folder', exact: true }).click()
  await page.getByLabel('Folder path').fill('Deep/Arbitrary/Folder')
  await page.getByRole('dialog').getByRole('button', { name: 'Create folder', exact: true }).click()
  await expect(page.locator('.tree-label').filter({ hasText: 'Deep' })).toBeVisible()
  await page.screenshot({ path: 'test-results/local-dir-connected.png', fullPage: true })
  expect(errors).toEqual([])
})
